spring:
    jpa:
      database: ${spring_jpa_database:POSTGRESQL}
      show-sql: ${spring_jpa_show_sql:true}
      hibernate:
          format_sql: ${spring_jpa_hibernate_format_sql:true}
          ddl-auto: ${spring_jpa_hibernate_ddl_auto:validate}
      properties:
          hibernate:
              default_schema: ${spring_jpa_properties_hibernate_default_schema:hackathon}

